from django.db import models

# Create your models here.

class Sqa(models.Model):
    id = models.AutoField(primary_key = True)
    sys_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    module_name = models.CharField(max_length=300)
    module_id = models.CharField(max_length=300)
    software_version = models.CharField(max_length=300)
    sqa_certificate_no = models.CharField(max_length=300)
    request_date = models.DateTimeField(auto_now_add=False)
    urd = models.TextField(null=True)
    srs = models.TextField(null=True)
    sdd = models.TextField(null=True)
    rtm = models.TextField(null=True)
    stp = models.TextField(null=True)
    unit_test = models.TextField(null=True)
    static_analysis_report = models.TextField(null=True)
    assertion_density = models.TextField(null=True)
    eng_change_proposal = models.TextField(null=True)
    bugs_observation = models.TextField(null=True)
    cyclomatic_complexity = models.TextField(null=True)
    code_coverage = models.TextField(null=True)
    functional_testing = models.TextField(null=True)
    formal_testing = models.TextField(null=True)
    status = models.CharField(max_length=300)
    due_date = models.DateTimeField(auto_now_add=False)
    audit_completion_date = models.DateTimeField(auto_now_add=False)
    organization = models.CharField(max_length=300, null= True)
    software_type = models.CharField(max_length=300, null= True)
    remarks = models.TextField()
    svc_no = models.CharField(max_length=300, null=True)
    svc_date = models.DateTimeField(auto_now_add=False, null=True)
    received_date = models.DateTimeField(auto_now_add=False, null=True)
    revision_no = models.CharField(max_length=300, null=True)
    revision_date = models.DateTimeField(auto_now_add=False, null=True)
    purpose = models.CharField(max_length=300, null=True)
    set_no = models.CharField(max_length=300, null=True)
    software_size = models.CharField(max_length=300, null=True)
    installation_date = models.DateTimeField(auto_now_add=False, null=True)
    attachment = models.TextField(null=True)

class SqaHistory(models.Model):
    id = models.AutoField(primary_key = True)
    sys_type = models.CharField(max_length=300)
    system_name = models.CharField(max_length=300)
    module_name = models.CharField(max_length=300)
    module_id = models.CharField(max_length=300)
    software_version = models.CharField(max_length=300)
    sqa_certificate_no = models.CharField(max_length=300)
    request_date = models.DateTimeField(auto_now_add=False)
    urd = models.TextField(null=True)
    srs = models.TextField(null=True)
    sdd = models.TextField(null=True)
    rtm = models.TextField(null=True)
    stp = models.TextField(null=True)
    unit_test = models.TextField(null=True)
    static_analysis_report = models.TextField(null=True)
    assertion_density = models.TextField(null=True)
    eng_change_proposal = models.TextField(null=True)
    bugs_observation = models.TextField(null=True)
    cyclomatic_complexity = models.TextField(null=True)
    code_coverage = models.TextField(null=True)
    functional_testing = models.TextField(null=True)
    formal_testing = models.TextField(null=True)
    status = models.CharField(max_length=300)
    due_date = models.DateTimeField(auto_now_add=False)
    audit_completion_date = models.DateTimeField(auto_now_add=False)
    organization = models.CharField(max_length=300, null= True)
    software_type = models.CharField(max_length=300, null= True)
    remarks = models.TextField()
    sqa = models.IntegerField()
    svc_no = models.CharField(max_length=300, null=True)
    svc_date = models.DateTimeField(auto_now_add=False, null=True)
    received_date = models.DateTimeField(auto_now_add=False, null=True)
    revision_no = models.CharField(max_length=300, null=True)
    revision_date = models.DateTimeField(auto_now_add=False, null=True)
    purpose = models.CharField(max_length=300, null=True)
    set_no = models.CharField(max_length=300, null=True)
    software_size = models.CharField(max_length=300, null=True)
    installation_date = models.DateTimeField(auto_now_add=False, null=True)
    attachment = models.TextField(null=True)