from os import system
from django.db import models


# Create your models here.
class ProductionSystemStatus(models.Model):
    system = models.CharField(max_length=300)
    organization = models.CharField(max_length=300)
    set_id = models.CharField(max_length=300)
    blt_date = models.DateTimeField(auto_now_add=False, null=True)
    testing_date = models.DateTimeField(auto_now_add=False, null=True)
    sys_type = models.CharField(max_length=300, null=True)
    blt_status = models.CharField(max_length=300)
    blt_remarks = models.TextField(null=True)
    pre_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_hil_status = models.CharField(max_length=300)
    pre_hil_remarks =  models.TextField(null=True)
    vibaration_date = models.DateTimeField(auto_now_add=False, null=True)
    vibaration_status = models.CharField(max_length=300)
    vibaration_remarks = models.TextField(null=True)
    post_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    post_hil_status = models.CharField(max_length=300)
    post_hil_remarks = models.TextField(null=True)
    fgt_date = models.DateTimeField(auto_now_add=False, null=True)
    fgt_status = models.CharField(max_length=300)
    fgt_remarks = models.TextField(null=True)
    final_integration_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integration_status = models.CharField(max_length=300)
    final_integration_remarks = models.TextField(null=True)
    bhd_date = models.DateTimeField(auto_now_add=False, null=True)
    bhd_status = models.CharField(max_length=300)
    bhd_remarks =models.TextField(null=True)
    fqm_date = models.DateTimeField(auto_now_add=False, null=True)
    fqm_status = models.CharField(max_length=300)
    fqm_remarks = models.TextField(null=True)
    qm_certification_date = models.DateTimeField(auto_now_add=False, null=True)
    qm_certification_status = models.CharField(max_length=300)
    qm_certification_remarks = models.TextField(null=True)
    attachment = models.TextField(null=True)
    remarks = models.TextField(null=True)
    isActive = models.IntegerField(default=0, null=False)
    Created_at = models.DateTimeField(auto_now_add=True)
    cgbalancing_date = models.DateTimeField(auto_now_add=False, null=True)
    cgbalancing_date_status = models.CharField(max_length=300, null=True)
    cgbalancing_date_remarks = models.TextField(null=True)
    enduser_date = models.DateTimeField(auto_now_add=False, null=True)
    enduser_status = models.CharField(max_length=300, null=True)
    enduser_remarks = models.TextField(null=True)
    incapsulation_date = models.DateTimeField(auto_now_add=False, null=True)
    incapsulation_status = models.CharField(max_length=300, null=True)
    incapsulation_remarks = models.TextField(null=True)
    sys_align_Date = models.DateTimeField(auto_now_add=False, null=True)
    sys_align_status = models.CharField(max_length=300, null=True)
    sys_align_remarks = models.TextField(null=True)
    testing_type = models.CharField(max_length=300, null=True)
    emp_proofing = models.CharField(max_length=300, null=True)
    func_tst = models.CharField(max_length=300, null=True)
    func_tst_dummy_bird = models.CharField(max_length=300, null=True)
    road_test = models.CharField(max_length=300, null=True)
    post_road_test = models.CharField(max_length=300, null=True)
    integrated_operation = models.CharField(max_length=300, null=True)
    rain_test = models.CharField(max_length=300, null=True)
    pre_user_inspection = models.CharField(max_length=300, null=True)
    final_integrated_testing = models.CharField(max_length=300, null=True)
    load_unload_on_mlv_hlf = models.CharField(max_length=300, null=True)

    emp_proofing_date = models.DateTimeField(auto_now_add=False, null=True)
    emp_proofing_remarks = models.TextField(null=True)
    func_tst_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_remarks = models.TextField(null=True)
    func_tst_dummy_bird_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_dummy_bird_remarks = models.CharField(max_length=20000, null=True)
    road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    road_test_remarks = models.TextField(null=True)
    post_road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    post_road_test_remarks = models.TextField(null=True)
    integrated_operation_date = models.DateTimeField(auto_now_add=False, null=True)
    integrated_operation_remarks = models.TextField(null=True)
    rain_test_date = models.DateTimeField(auto_now_add=False, null=True)
    rain_test_remarks = models.TextField(null=True)
    pre_user_inspection_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_user_inspection_remarks = models.TextField(null=True)
    final_integrated_testing_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integrated_testing_remarks = models.TextField(null=True)
    load_unload_on_mlv_hlf_date = models.DateTimeField(auto_now_add=False, null=True)
    load_unload_on_mlv_hlf_remarks = models.TextField(null=True)
    user_id = models.IntegerField(null=True)


class ProductionSystemStatusHistory(models.Model):
    prod_id = models.IntegerField(null=True)
    system = models.CharField(max_length=300)
    organization = models.CharField(max_length=300)
    set_id = models.CharField(max_length=300)
    blt_date = models.DateTimeField(auto_now_add=False, null=True)
    testing_date = models.DateTimeField(auto_now_add=False, null=True)
    sys_type = models.CharField(max_length=300, null=True)
    blt_status = models.CharField(max_length=300)
    blt_remarks = models.TextField(null=True)
    pre_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_hil_status = models.CharField(max_length=300)
    pre_hil_remarks =  models.TextField(null=True)
    vibaration_date = models.DateTimeField(auto_now_add=False, null=True)
    vibaration_status = models.CharField(max_length=300)
    vibaration_remarks = models.TextField(null=True)
    post_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    post_hil_status = models.CharField(max_length=300)
    post_hil_remarks = models.TextField(null=True)
    fgt_date = models.DateTimeField(auto_now_add=False, null=True)
    fgt_status = models.CharField(max_length=300)
    fgt_remarks = models.TextField(null=True)
    final_integration_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integration_status = models.CharField(max_length=300)
    final_integration_remarks = models.TextField(null=True)
    bhd_date = models.DateTimeField(auto_now_add=False, null=True)
    bhd_status = models.CharField(max_length=300)
    bhd_remarks =models.TextField(null=True)
    fqm_date = models.DateTimeField(auto_now_add=False, null=True)
    fqm_status = models.CharField(max_length=300)
    fqm_remarks = models.TextField(null=True)
    qm_certification_date = models.DateTimeField(auto_now_add=False, null=True)
    qm_certification_status = models.CharField(max_length=300)
    qm_certification_remarks = models.TextField(null=True)
    attachment = models.TextField(null=True)
    remarks = models.TextField(null=True)
    isActive = models.IntegerField(default=0, null=False)
    Created_at = models.DateTimeField(auto_now_add=True)
    cgbalancing_date = models.DateTimeField(auto_now_add=False, null=True)
    cgbalancing_date_status = models.CharField(max_length=300, null=True)
    cgbalancing_date_remarks = models.TextField(null=True)
    enduser_date = models.DateTimeField(auto_now_add=False, null=True)
    enduser_status = models.CharField(max_length=300, null=True)
    enduser_remarks = models.TextField(null=True)
    incapsulation_date = models.DateTimeField(auto_now_add=False, null=True)
    incapsulation_status = models.CharField(max_length=300, null=True)
    incapsulation_remarks = models.TextField(null=True)
    sys_align_Date = models.DateTimeField(auto_now_add=False, null=True)
    sys_align_status = models.CharField(max_length=300, null=True)
    sys_align_remarks = models.TextField(null=True)
    testing_type = models.CharField(max_length=300, null=True)
    emp_proofing = models.CharField(max_length=300, null=True)
    func_tst = models.CharField(max_length=300, null=True)
    func_tst_dummy_bird = models.CharField(max_length=300, null=True)
    road_test = models.CharField(max_length=300, null=True)
    post_road_test = models.CharField(max_length=300, null=True)
    integrated_operation = models.CharField(max_length=300, null=True)
    rain_test = models.CharField(max_length=300, null=True)
    pre_user_inspection = models.CharField(max_length=300, null=True)
    final_integrated_testing = models.CharField(max_length=300, null=True)
    load_unload_on_mlv_hlf = models.CharField(max_length=300, null=True)

    emp_proofing_date = models.DateTimeField(auto_now_add=False, null=True)
    emp_proofing_remarks = models.TextField(null=True)
    func_tst_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_remarks = models.TextField(null=True)
    func_tst_dummy_bird_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_dummy_bird_remarks = models.CharField(max_length=20000, null=True)
    road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    road_test_remarks = models.TextField(null=True)
    post_road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    post_road_test_remarks = models.TextField(null=True)
    integrated_operation_date = models.DateTimeField(auto_now_add=False, null=True)
    integrated_operation_remarks = models.TextField(null=True)
    rain_test_date = models.DateTimeField(auto_now_add=False, null=True)
    rain_test_remarks = models.TextField(null=True)
    pre_user_inspection_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_user_inspection_remarks = models.TextField(null=True)
    final_integrated_testing_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integrated_testing_remarks = models.TextField(null=True)
    load_unload_on_mlv_hlf_date = models.DateTimeField(auto_now_add=False, null=True)
    load_unload_on_mlv_hlf_remarks = models.TextField(null=True)
    user_id = models.IntegerField(null=True)


class FlightSystemStatus(models.Model):
    system = models.CharField(max_length=300)
    organization = models.CharField(max_length=300)
    set_id = models.CharField(max_length=300)
    blt_date = models.DateTimeField(auto_now_add=False, null=True)
    testing_date = models.DateTimeField(auto_now_add=False, null=True)
    sys_type = models.CharField(max_length=300, null=True)
    blt_status = models.CharField(max_length=300)
    blt_remarks = models.TextField(null=True)
    pre_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_hil_status = models.CharField(max_length=300)
    pre_hil_remarks =  models.TextField(null=True)
    vibaration_date = models.DateTimeField(auto_now_add=False, null=True)
    vibaration_status = models.CharField(max_length=300)
    vibaration_remarks = models.TextField(null=True)
    post_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    post_hil_status = models.CharField(max_length=300)
    post_hil_remarks = models.TextField(null=True)
    fgt_date = models.DateTimeField(auto_now_add=False, null=True)
    fgt_status = models.CharField(max_length=300)
    fgt_remarks = models.TextField(null=True)
    final_integration_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integration_status = models.CharField(max_length=300)
    final_integration_remarks = models.TextField(null=True)
    bhd_date = models.DateTimeField(auto_now_add=False, null=True)
    bhd_status = models.CharField(max_length=300)
    bhd_remarks =models.TextField(null=True)
    fqm_date = models.DateTimeField(auto_now_add=False, null=True)
    fqm_status = models.CharField(max_length=300)
    fqm_remarks = models.TextField(null=True)
    qm_certification_date = models.DateTimeField(auto_now_add=False, null=True)
    qm_certification_status = models.CharField(max_length=300)
    qm_certification_remarks = models.TextField(null=True)
    attachment = models.TextField(null=True)
    remarks = models.TextField(null=True)
    isActive = models.IntegerField(default=0, null=False)
    Created_at = models.DateTimeField(auto_now_add=True)
    cgbalancing_date = models.DateTimeField(auto_now_add=False, null=True)
    cgbalancing_date_status = models.CharField(max_length=300, null=True)
    cgbalancing_date_remarks = models.TextField(null=True)
    launchact_date = models.DateTimeField(auto_now_add=False, null=True)
    launchact_status = models.CharField(max_length=300, null=True)
    launchact_remarks = models.TextField(null=True)
    incapsulation_date = models.DateTimeField(auto_now_add=False, null=True)
    incapsulation_status = models.CharField(max_length=300, null=True)
    incapsulation_remarks = models.TextField(null=True)
    sys_align_Date = models.DateTimeField(auto_now_add=False, null=True)
    sys_align_status = models.CharField(max_length=300, null=True)
    sys_align_remarks = models.TextField(null=True)
    testing_type = models.CharField(max_length=300, null=True)
    emp_proofing = models.CharField(max_length=300, null=True)
    func_tst = models.CharField(max_length=300, null=True)
    func_tst_dummy_bird = models.CharField(max_length=300, null=True)
    road_test = models.CharField(max_length=300, null=True)
    post_road_test = models.CharField(max_length=300, null=True)
    integrated_operation = models.CharField(max_length=300, null=True)
    rain_test = models.CharField(max_length=300, null=True)
    pre_user_inspection = models.CharField(max_length=300, null=True)
    final_integrated_testing = models.CharField(max_length=300, null=True)
    load_unload_on_mlv_hlf = models.CharField(max_length=300, null=True)

    emp_proofing_date = models.DateTimeField(auto_now_add=False, null=True)
    emp_proofing_remarks = models.TextField(null=True)
    func_tst_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_remarks = models.TextField(null=True)
    func_tst_dummy_bird_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_dummy_bird_remarks = models.TextField(null=True)
    road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    road_test_remarks = models.TextField(null=True)
    post_road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    post_road_test_remarks = models.TextField(null=True)
    integrated_operation_date = models.DateTimeField(auto_now_add=False, null=True)
    integrated_operation_remarks = models.TextField(null=True)
    rain_test_date = models.DateTimeField(auto_now_add=False, null=True)
    rain_test_remarks = models.TextField(null=True)
    pre_user_inspection_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_user_inspection_remarks = models.TextField(null=True)
    final_integrated_testing_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integrated_testing_remarks = models.TextField(null=True)
    load_unload_on_mlv_hlf_date = models.DateTimeField(auto_now_add=False, null=True)
    load_unload_on_mlv_hlf_remarks = models.TextField(null=True)
    user_id = models.IntegerField(null=True)


    blt_sub_status = models.TextField(null=True)



class FlightSystemStatusHistory(models.Model):
    f_id = models.IntegerField(null=True)
    system = models.CharField(max_length=300)
    organization = models.CharField(max_length=300)
    set_id = models.CharField(max_length=300)
    blt_date = models.DateTimeField(auto_now_add=False, null=True)
    testing_date = models.DateTimeField(auto_now_add=False, null=True)
    sys_type = models.CharField(max_length=300, null=True)
    blt_status = models.CharField(max_length=300)
    blt_remarks = models.TextField(null=True)
    pre_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_hil_status = models.CharField(max_length=300)
    pre_hil_remarks =  models.TextField(null=True)
    vibaration_date = models.DateTimeField(auto_now_add=False, null=True)
    vibaration_status = models.CharField(max_length=300)
    vibaration_remarks = models.TextField(null=True)
    post_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    post_hil_status = models.CharField(max_length=300)
    post_hil_remarks = models.TextField(null=True)
    fgt_date = models.DateTimeField(auto_now_add=False, null=True)
    fgt_status = models.CharField(max_length=300)
    fgt_remarks = models.TextField(null=True)
    final_integration_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integration_status = models.CharField(max_length=300)
    final_integration_remarks = models.TextField(null=True)
    bhd_date = models.DateTimeField(auto_now_add=False, null=True)
    bhd_status = models.CharField(max_length=300)
    bhd_remarks =models.TextField(null=True)
    fqm_date = models.DateTimeField(auto_now_add=False, null=True)
    fqm_status = models.CharField(max_length=300)
    fqm_remarks = models.TextField(null=True)
    qm_certification_date = models.DateTimeField(auto_now_add=False, null=True)
    qm_certification_status = models.CharField(max_length=300)
    qm_certification_remarks = models.TextField(null=True)
    attachment = models.TextField(null=True)
    remarks = models.TextField(null=True)
    isActive = models.IntegerField(default=0, null=False)
    Created_at = models.DateTimeField(auto_now_add=True)
    cgbalancing_date = models.DateTimeField(auto_now_add=False, null=True)
    cgbalancing_date_status = models.CharField(max_length=300, null=True)
    cgbalancing_date_remarks = models.TextField(null=True)
    launchact_date = models.DateTimeField(auto_now_add=False, null=True)
    launchact_status = models.CharField(max_length=300, null=True)
    launchact_remarks = models.TextField(null=True)
    incapsulation_date = models.DateTimeField(auto_now_add=False, null=True)
    incapsulation_status = models.CharField(max_length=300, null=True)
    incapsulation_remarks = models.TextField(null=True)
    sys_align_Date = models.DateTimeField(auto_now_add=False, null=True)
    sys_align_status = models.CharField(max_length=300, null=True)
    sys_align_remarks = models.TextField(null=True)
    testing_type = models.CharField(max_length=300, null=True)
    emp_proofing = models.CharField(max_length=300, null=True)
    func_tst = models.CharField(max_length=300, null=True)
    func_tst_dummy_bird = models.CharField(max_length=300, null=True)
    road_test = models.CharField(max_length=300, null=True)
    post_road_test = models.CharField(max_length=300, null=True)
    integrated_operation = models.CharField(max_length=300, null=True)
    rain_test = models.CharField(max_length=300, null=True)
    pre_user_inspection = models.CharField(max_length=300, null=True)
    final_integrated_testing = models.CharField(max_length=300, null=True)
    load_unload_on_mlv_hlf = models.CharField(max_length=300, null=True)

    emp_proofing_date = models.DateTimeField(auto_now_add=False, null=True)
    emp_proofing_remarks = models.TextField(null=True)
    func_tst_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_remarks = models.TextField(null=True)
    func_tst_dummy_bird_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_dummy_bird_remarks = models.TextField(null=True)
    road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    road_test_remarks = models.TextField(null=True)
    post_road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    post_road_test_remarks = models.TextField(null=True)
    integrated_operation_date = models.DateTimeField(auto_now_add=False, null=True)
    integrated_operation_remarks = models.TextField(null=True)
    rain_test_date = models.DateTimeField(auto_now_add=False, null=True)
    rain_test_remarks = models.TextField(null=True)
    pre_user_inspection_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_user_inspection_remarks = models.TextField(null=True)
    final_integrated_testing_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integrated_testing_remarks = models.TextField(null=True)
    load_unload_on_mlv_hlf_date = models.DateTimeField(auto_now_add=False, null=True)
    load_unload_on_mlv_hlf_remarks = models.TextField(null=True)
    user_id = models.IntegerField(null=True)

class RelifingSystemStatus(models.Model):
    system = models.CharField(max_length=300)
    organization = models.CharField(max_length=300)
    set_id = models.CharField(max_length=300)
    blt_date = models.DateTimeField(auto_now_add=False, null=True)
    testing_date = models.DateTimeField(auto_now_add=False, null=True)
    sys_type = models.CharField(max_length=300, null=True)
    blt_status = models.CharField(max_length=300)
    blt_remarks = models.TextField(null=True)
    pre_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_hil_status = models.CharField(max_length=300)
    pre_hil_remarks =  models.TextField(null=True)
    vibaration_date = models.DateTimeField(auto_now_add=False, null=True)
    vibaration_status = models.CharField(max_length=300)
    vibaration_remarks = models.TextField(null=True)
    post_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    post_hil_status = models.CharField(max_length=300)
    post_hil_remarks = models.TextField(null=True)
    fgt_date = models.DateTimeField(auto_now_add=False, null=True)
    fgt_status = models.CharField(max_length=300)
    fgt_remarks = models.TextField(null=True)
    final_integration_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integration_status = models.CharField(max_length=300)
    final_integration_remarks = models.TextField(null=True)
    bhd_date = models.DateTimeField(auto_now_add=False, null=True)
    bhd_status = models.CharField(max_length=300)
    bhd_remarks =models.TextField(null=True)
    fqm_date = models.DateTimeField(auto_now_add=False, null=True)
    fqm_status = models.CharField(max_length=300)
    fqm_remarks = models.TextField(null=True)
    qm_certification_date = models.DateTimeField(auto_now_add=False, null=True)
    qm_certification_status = models.CharField(max_length=300)
    qm_certification_remarks = models.TextField(null=True)
    attachment = models.TextField(null=True)
    remarks = models.TextField(null=True)
    isActive = models.IntegerField(default=0, null=False)
    Created_at = models.DateTimeField(auto_now_add=True)
    cgbalancing_date = models.DateTimeField(auto_now_add=False, null=True)
    cgbalancing_date_status = models.CharField(max_length=300, null=True)
    cgbalancing_date_remarks = models.TextField(null=True)
    enduser_date = models.DateTimeField(auto_now_add=False, null=True)
    enduser_status = models.CharField(max_length=300, null=True)
    enduser_remarks = models.TextField(null=True)
    incapsulation_date = models.DateTimeField(auto_now_add=False, null=True)
    incapsulation_status = models.CharField(max_length=300, null=True)
    incapsulation_remarks = models.TextField(null=True)
    sys_align_Date = models.DateTimeField(auto_now_add=False, null=True)
    sys_align_status = models.CharField(max_length=300, null=True)
    sys_align_remarks = models.TextField(null=True)
    testing_type = models.CharField(max_length=300, null=True)
    emp_proofing = models.CharField(max_length=300, null=True)
    func_tst = models.CharField(max_length=300, null=True)
    func_tst_dummy_bird = models.CharField(max_length=300, null=True)
    road_test = models.CharField(max_length=300, null=True)
    post_road_test = models.CharField(max_length=300, null=True)
    integrated_operation = models.CharField(max_length=300, null=True)
    rain_test = models.CharField(max_length=300, null=True)
    pre_user_inspection = models.CharField(max_length=300, null=True)
    final_integrated_testing = models.CharField(max_length=300, null=True)
    load_unload_on_mlv_hlf = models.CharField(max_length=300, null=True)

    emp_proofing_date = models.DateTimeField(auto_now_add=False, null=True)
    emp_proofing_remarks = models.TextField(null=True)
    func_tst_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_remarks = models.TextField(null=True)
    func_tst_dummy_bird_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_dummy_bird_remarks = models.TextField(null=True)
    road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    road_test_remarks = models.TextField(null=True)
    post_road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    post_road_test_remarks = models.TextField(null=True)
    integrated_operation_date = models.DateTimeField(auto_now_add=False, null=True)
    integrated_operation_remarks = models.TextField(null=True)
    rain_test_date = models.DateTimeField(auto_now_add=False, null=True)
    rain_test_remarks = models.TextField(null=True)
    pre_user_inspection_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_user_inspection_remarks = models.TextField(null=True)
    final_integrated_testing_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integrated_testing_remarks = models.TextField(null=True)
    load_unload_on_mlv_hlf_date = models.DateTimeField(auto_now_add=False, null=True)
    load_unload_on_mlv_hlf_remarks = models.TextField(null=True)
    user_id = models.IntegerField(null=True)


class RelifingSystemStatusHistory(models.Model):
    r_id = models.IntegerField(null=True)
    system = models.CharField(max_length=300)
    organization = models.CharField(max_length=300)
    set_id = models.CharField(max_length=300)
    blt_date = models.DateTimeField(auto_now_add=False, null=True)
    testing_date = models.DateTimeField(auto_now_add=False, null=True)
    sys_type = models.CharField(max_length=300, null=True)
    blt_status = models.CharField(max_length=300)
    blt_remarks = models.TextField(null=True)
    pre_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_hil_status = models.CharField(max_length=300)
    pre_hil_remarks =  models.TextField(null=True)
    vibaration_date = models.DateTimeField(auto_now_add=False, null=True)
    vibaration_status = models.CharField(max_length=300)
    vibaration_remarks = models.TextField(null=True)
    post_hil_date = models.DateTimeField(auto_now_add=False, null=True)
    post_hil_status = models.CharField(max_length=300)
    post_hil_remarks = models.TextField(null=True)
    fgt_date = models.DateTimeField(auto_now_add=False, null=True)
    fgt_status = models.CharField(max_length=300)
    fgt_remarks = models.TextField(null=True)
    final_integration_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integration_status = models.CharField(max_length=300)
    final_integration_remarks = models.TextField(null=True)
    bhd_date = models.DateTimeField(auto_now_add=False, null=True)
    bhd_status = models.CharField(max_length=300)
    bhd_remarks =models.TextField(null=True)
    fqm_date = models.DateTimeField(auto_now_add=False, null=True)
    fqm_status = models.CharField(max_length=300)
    fqm_remarks = models.TextField(null=True)
    qm_certification_date = models.DateTimeField(auto_now_add=False, null=True)
    qm_certification_status = models.CharField(max_length=300)
    qm_certification_remarks = models.TextField(null=True)
    attachment = models.TextField(null=True)
    remarks = models.TextField(null=True)
    isActive = models.IntegerField(default=0, null=False)
    Created_at = models.DateTimeField(auto_now_add=True)
    cgbalancing_date = models.DateTimeField(auto_now_add=False, null=True)
    cgbalancing_date_status = models.CharField(max_length=300, null=True)
    cgbalancing_date_remarks = models.TextField(null=True)
    enduser_date = models.DateTimeField(auto_now_add=False, null=True)
    enduser_status = models.CharField(max_length=300, null=True)
    enduser_remarks = models.TextField(null=True)
    incapsulation_date = models.DateTimeField(auto_now_add=False, null=True)
    incapsulation_status = models.CharField(max_length=300, null=True)
    incapsulation_remarks = models.TextField(null=True)
    sys_align_Date = models.DateTimeField(auto_now_add=False, null=True)
    sys_align_status = models.CharField(max_length=300, null=True)
    sys_align_remarks = models.TextField(null=True)
    testing_type = models.CharField(max_length=300, null=True)
    emp_proofing = models.CharField(max_length=300, null=True)
    func_tst = models.CharField(max_length=300, null=True)
    func_tst_dummy_bird = models.CharField(max_length=300, null=True)
    road_test = models.CharField(max_length=300, null=True)
    post_road_test = models.CharField(max_length=300, null=True)
    integrated_operation = models.CharField(max_length=300, null=True)
    rain_test = models.CharField(max_length=300, null=True)
    pre_user_inspection = models.CharField(max_length=300, null=True)
    final_integrated_testing = models.CharField(max_length=300, null=True)
    load_unload_on_mlv_hlf = models.CharField(max_length=300, null=True)

    emp_proofing_date = models.DateTimeField(auto_now_add=False, null=True)
    emp_proofing_remarks = models.TextField(null=True)
    func_tst_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_remarks = models.TextField(null=True)
    func_tst_dummy_bird_date = models.DateTimeField(auto_now_add=False, null=True)
    func_tst_dummy_bird_remarks = models.TextField(null=True)
    road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    road_test_remarks = models.TextField(null=True)
    post_road_test_date = models.DateTimeField(auto_now_add=False, null=True)
    post_road_test_remarks = models.TextField(null=True)
    integrated_operation_date = models.DateTimeField(auto_now_add=False, null=True)
    integrated_operation_remarks = models.TextField(null=True)
    rain_test_date = models.DateTimeField(auto_now_add=False, null=True)
    rain_test_remarks = models.TextField(null=True)
    pre_user_inspection_date = models.DateTimeField(auto_now_add=False, null=True)
    pre_user_inspection_remarks = models.TextField(null=True)
    final_integrated_testing_date = models.DateTimeField(auto_now_add=False, null=True)
    final_integrated_testing_remarks = models.TextField(null=True)
    load_unload_on_mlv_hlf_date = models.DateTimeField(auto_now_add=False, null=True)
    load_unload_on_mlv_hlf_remarks = models.TextField(null=True)
    user_id = models.IntegerField(null=True)
