from .models import *
from rest_framework.serializers import Serializer
from rest_framework.fields import CharField, IntegerField, DateTimeField


# Add Product Serializer
class ProductionSystemSerialzer(Serializer):
    id = IntegerField()
    system = CharField()
    organization = CharField()
    set_id = CharField()
    blt_date = DateTimeField()
    testing_date = DateTimeField()
    sys_type = CharField()
    blt_status = CharField()
    pre_hil_date = CharField()
    pre_hil_status = CharField()
    vibaration_date = CharField()
    vibaration_status = CharField()
    post_hil_date = CharField()
    post_hil_status = CharField()
    fgt_date = CharField()
    fgt_status = CharField()
    final_integration_date = CharField()
    final_integration_status = CharField()
    bhd_date = CharField()
    bhd_status = CharField()
    fqm_date = CharField()
    fqm_status = CharField()
    qm_certification_date = CharField()
    qm_certification_status = CharField()
    attachment = CharField()
    remarks = CharField()
    Created_at = DateTimeField()


class FlightSystemSerialzer(Serializer):
    id = IntegerField()
    system = CharField()
    organization = CharField()
    set_id = CharField()
    blt_date = DateTimeField()
    testing_date = DateTimeField()
    sys_type = CharField()
    blt_status = CharField()
    pre_hil_date = CharField()
    pre_hil_status = CharField()
    vibaration_date = CharField()
    vibaration_status = CharField()
    post_hil_date = CharField()
    post_hil_status = CharField()
    fgt_date = CharField()
    fgt_status = CharField()
    final_integration_date = CharField()
    final_integration_status = CharField()
    bhd_date = CharField()
    bhd_status = CharField()
    fqm_date = CharField()
    fqm_status = CharField()
    qm_certification_date = CharField()
    qm_certification_status = CharField()
    attachment = CharField()
    remarks = CharField()
    Created_at = DateTimeField()


class RelifingSystemSerialzer(Serializer):
    id = IntegerField()
    system = CharField()
    organization = CharField()
    set_id = CharField()
    blt_date = DateTimeField()
    testing_date = DateTimeField()
    sys_type = CharField()
    blt_status = CharField()
    pre_hil_date = CharField()
    pre_hil_status = CharField()
    vibaration_date = CharField()
    vibaration_status = CharField()
    post_hil_date = CharField()
    post_hil_status = CharField()
    fgt_date = CharField()
    fgt_status = CharField()
    final_integration_date = CharField()
    final_integration_status = CharField()
    bhd_date = CharField()
    bhd_status = CharField()
    fqm_date = CharField()
    fqm_status = CharField()
    qm_certification_date = CharField()
    qm_certification_status = CharField()
    attachment = CharField()
    remarks = CharField()
    Created_at = DateTimeField()
