# Generated by Django 3.2.1 on 2022-09-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightsystemstatus',
            old_name='final_integration_st',
            new_name='final_integration_status',
        ),
        migrations.RenameField(
            model_name='flightsystemstatus',
            old_name='qm_certification_st',
            new_name='qm_certification_status',
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='bhd_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='blt_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='fgt_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='final_integration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='fqm_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='isActive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='post_hil_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='pre_hil_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='qm_certification_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='vibaration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flightsystemstatus',
            name='bhd_status',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='flightsystemstatus',
            name='fqm_status',
            field=models.CharField(max_length=300),
        ),
    ]
