# Generated by Django 3.2.1 on 2022-10-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20220925_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSystemStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField(null=True)),
                ('system', models.CharField(max_length=300)),
                ('organization', models.CharField(max_length=300)),
                ('set_id', models.CharField(max_length=300)),
                ('blt_date', models.DateTimeField(null=True)),
                ('blt_status', models.CharField(max_length=300)),
                ('pre_hil_date', models.DateTimeField(null=True)),
                ('pre_hil_status', models.CharField(max_length=300)),
                ('vibaration_date', models.DateTimeField(null=True)),
                ('vibaration_status', models.CharField(max_length=300)),
                ('post_hil_date', models.DateTimeField(null=True)),
                ('post_hil_status', models.CharField(max_length=300)),
                ('fgt_date', models.DateTimeField(null=True)),
                ('fgt_status', models.CharField(max_length=300)),
                ('final_integration_date', models.DateTimeField(null=True)),
                ('final_integration_status', models.CharField(max_length=300)),
                ('bhd_date', models.DateTimeField(null=True)),
                ('bhd_status', models.CharField(max_length=300)),
                ('fqm_date', models.DateTimeField(null=True)),
                ('fqm_status', models.CharField(max_length=300)),
                ('qm_certification_date', models.DateTimeField(null=True)),
                ('qm_certification_status', models.CharField(max_length=300)),
                ('attachment', models.TextField()),
                ('remarks', models.TextField()),
                ('isActive', models.IntegerField(default=0)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
