# Generated by Django 3.2.1 on 2022-11-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_relifingsystemstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsystemstatus',
            name='sys_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatus',
            name='testing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatushistory',
            name='sys_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='flightsystemstatushistory',
            name='testing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productionsystemstatus',
            name='sys_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productionsystemstatus',
            name='testing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='productionsystemstatushistory',
            name='sys_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productionsystemstatushistory',
            name='testing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='relifingsystemstatus',
            name='sys_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='relifingsystemstatus',
            name='testing_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='relifingsystemstatushistory',
            name='sys_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='relifingsystemstatushistory',
            name='testing_date',
            field=models.DateTimeField(null=True),
        ),
    ]
