# Generated by Django 3.2.1 on 2024-03-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_type', models.CharField(max_length=300)),
                ('sys_name', models.CharField(max_length=300)),
                ('products', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('audit_completion_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
