# Generated by Django 3.2.1 on 2024-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emc',
            old_name='products',
            new_name='product_tests',
        ),
        migrations.AddField(
            model_name='emc',
            name='product',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
