# Generated by Django 3.2.1 on 2024-04-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0002_auto_20240330_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emc',
            name='product_tests',
        ),
        migrations.AddField(
            model_name='emc',
            name='compliance_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='module',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='platform',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='report_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='selected_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='test',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='test_compliance',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='test_conducted',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='test_requirements',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
