# Generated by Django 3.2.1 on 2024-04-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0003_auto_20240401_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='emc',
            name='organization',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
