# Generated by Django 3.2.1 on 2024-04-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0004_emc_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emc',
            old_name='module',
            new_name='emc_id',
        ),
        migrations.RenameField(
            model_name='emc',
            old_name='platform',
            new_name='module_name',
        ),
        migrations.RenameField(
            model_name='emc',
            old_name='product',
            new_name='set_id',
        ),
        migrations.RemoveField(
            model_name='emc',
            name='audit_completion_date',
        ),
        migrations.RemoveField(
            model_name='emc',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='emc',
            name='selected_status',
        ),
        migrations.RemoveField(
            model_name='emc',
            name='test',
        ),
    ]
