# Generated by Django 3.2.1 on 2024-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0005_auto_20240428_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='emc',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
