# Generated by Django 3.2.1 on 2024-04-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0006_emc_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emc',
            old_name='emc_id',
            new_name='emi_emc_id',
        ),
    ]
