# Generated by Django 3.2.1 on 2024-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0007_rename_emc_id_emc_emi_emc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emc',
            name='ce_101',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='ce_102',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='ce_106',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_101',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_103',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_104',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_105',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_109',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_114',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_115',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_116',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_117',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='cs_118',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='re_101',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='re_102',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='re_103',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='rs_101',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='rs_103',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='rs_105',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
