# Generated by Django 3.2.1 on 2024-05-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0009_emchistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emc',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='emc',
            name='set_id',
        ),
        migrations.RemoveField(
            model_name='emchistory',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='emchistory',
            name='set_id',
        ),
        migrations.AddField(
            model_name='emc',
            name='compliance_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='design_version',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emc',
            name='lot_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emchistory',
            name='compliance_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='emchistory',
            name='design_version',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='emchistory',
            name='lot_no',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
