# Generated by Django 3.2.1 on 2022-09-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CespAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_id', models.IntegerField()),
                ('Organization', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=300)),
                ('certification_status', models.CharField(max_length=300)),
                ('previous_standard', models.CharField(max_length=300)),
                ('certification_validity', models.CharField(max_length=300)),
                ('audit_type', models.CharField(max_length=300)),
                ('planned_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_start_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_close_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_status', models.CharField(max_length=300)),
                ('standard', models.CharField(max_length=300)),
                ('remarks', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QmsAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_id', models.IntegerField()),
                ('Organization', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=300)),
                ('certification_status', models.CharField(max_length=300)),
                ('previous_standard', models.CharField(max_length=300)),
                ('certification_validity', models.CharField(max_length=300)),
                ('audit_type', models.CharField(max_length=300)),
                ('planned_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_start_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_close_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_status', models.CharField(max_length=300)),
                ('standard', models.CharField(max_length=300)),
                ('remarks', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
