# Generated by Django 3.2.1 on 2022-12-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CespAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_id', models.IntegerField()),
                ('Organization', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=300)),
                ('certification_status', models.CharField(max_length=300)),
                ('previous_standard', models.CharField(max_length=300)),
                ('certification_validity', models.CharField(max_length=300)),
                ('audit_type', models.CharField(max_length=300)),
                ('planned_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_start_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_close_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_status', models.CharField(max_length=300)),
                ('standard', models.CharField(max_length=300)),
                ('remarks', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QmsAudit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audit_id', models.IntegerField()),
                ('Organization', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=300)),
                ('setup', models.CharField(max_length=300, null=True)),
                ('certification_status', models.CharField(max_length=300)),
                ('previous_standard', models.CharField(max_length=300)),
                ('certification_validity_date', models.DateTimeField(db_index=True, null=True)),
                ('certification_validity_rescheduling_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_type', models.CharField(max_length=300)),
                ('planned_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_start_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_close_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_status', models.CharField(max_length=300)),
                ('standard', models.CharField(max_length=300)),
                ('remarks', models.TextField()),
                ('certification_setup', models.TextField(null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QmsAuditScheduled',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_no', models.IntegerField()),
                ('organization', models.CharField(max_length=300)),
                ('standard', models.TextField()),
                ('setup', models.CharField(max_length=300)),
                ('audit_due_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_done', models.CharField(max_length=100)),
                ('followup_done', models.CharField(max_length=100)),
                ('certifification_validity_date', models.DateTimeField(db_index=True, null=True)),
                ('certifification_validity_rescheduling_date', models.DateTimeField(db_index=True, null=True)),
                ('category', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('next_due_date', models.DateTimeField(db_index=True, null=True)),
                ('remarks', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QmsTrainingSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sr_no', models.IntegerField()),
                ('training_type', models.TextField()),
                ('training_start_date', models.DateTimeField(db_index=True, null=True)),
                ('training_end_date', models.DateTimeField(db_index=True, null=True)),
                ('trainer', models.CharField(max_length=300)),
                ('standards', models.TextField()),
                ('organizations', models.CharField(max_length=300)),
                ('setups', models.CharField(max_length=300)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
