# Generated by Django 3.2.1 on 2022-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qmsauditscheduled',
            name='audit_done',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qmsauditscheduled',
            name='category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='qmsauditscheduled',
            name='followup_done',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qmsauditscheduled',
            name='organization',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='qmsauditscheduled',
            name='sr_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qmsauditscheduled',
            name='status',
            field=models.CharField(max_length=300),
        ),
    ]
