# Generated by Django 3.2.1 on 2022-11-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmsaudit',
            name='certification_setup',
            field=models.TextField(null=True),
        ),
    ]
