# Generated by Django 3.2.1 on 2022-12-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qmsaudit',
            name='setup',
            field=models.CharField(max_length=300),
        ),
    ]
