from django.db import models


# Create your models here.
class Power(models.Model):
    id = models.AutoField(primary_key=True)
    system_type = models.CharField(max_length=300,null=True)
    module_name = models.CharField(max_length=300, null=True)
    pc_module_id = models.CharField(max_length=300, null=True)
    lot_no = models.CharField(max_length=300, null=True)
    design_version = models.CharField(max_length=300, null=True)
    power_compliance_status = models.CharField(max_length=900, null=True)
    pcs_ldc101 = models.CharField(max_length=300, null=True)
    pcs_ldc102 = models.CharField(max_length=300, null=True)
    pcs_ldc103 = models.CharField(max_length=300, null=True)
    pcs_ldc104 = models.CharField(max_length=300, null=True)
    pcs_ldc105 = models.CharField(max_length=300, null=True)
    pcs_ldc201 = models.CharField(max_length=300, null=True)
    pcs_ldc301 = models.CharField(max_length=300, null=True)
    pcs_ldc401 = models.CharField(max_length=300, null=True)
    pcs_ldc501 = models.CharField(max_length=300, null=True)
    pcs_ldc601 = models.CharField(max_length=300, null=True)
    pcs_ldc602 = models.CharField(max_length=300, null=True)
    compliance_status = models.CharField(max_length=300, null=True)
    report_status = models.CharField(max_length=300, null=True)
    compliance_date = models.DateTimeField(auto_now_add=False, null=True)
    remarks = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)


class PowerHistory(models.Model):
    id = models.AutoField(primary_key=True)
    power_id = models.IntegerField(null=True)
    system_type = models.CharField(max_length=300,null=True)
    module_name = models.CharField(max_length=300, null=True)
    pc_module_id = models.CharField(max_length=300, null=True)
    lot_no = models.CharField(max_length=300, null=True)
    design_version = models.CharField(max_length=300, null=True)
    power_compliance_status = models.CharField(max_length=900, null=True)
    pcs_ldc101 = models.CharField(max_length=300, null=True)
    pcs_ldc102 = models.CharField(max_length=300, null=True)
    pcs_ldc103 = models.CharField(max_length=300, null=True)
    pcs_ldc104 = models.CharField(max_length=300, null=True)
    pcs_ldc105 = models.CharField(max_length=300, null=True)
    pcs_ldc201 = models.CharField(max_length=300, null=True)
    pcs_ldc301 = models.CharField(max_length=300, null=True)
    pcs_ldc401 = models.CharField(max_length=300, null=True)
    pcs_ldc501 = models.CharField(max_length=300, null=True)
    pcs_ldc601 = models.CharField(max_length=300, null=True)
    pcs_ldc602 = models.CharField(max_length=300, null=True)
    compliance_status = models.CharField(max_length=300, null=True)
    report_status = models.CharField(max_length=300, null=True)
    compliance_date = models.DateTimeField(auto_now_add=False, null=True)
    remarks = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

