# Generated by Django 3.2.1 on 2023-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctrackingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField()),
                ('doc_name', models.CharField(max_length=500)),
                ('doc_type', models.CharField(max_length=500)),
                ('sender', models.CharField(max_length=100, null=True)),
                ('receive_date', models.DateTimeField(db_index=True, null=True)),
                ('marked_to', models.CharField(max_length=100, null=True)),
                ('marked_date', models.DateTimeField(db_index=True, null=True)),
                ('due_date', models.DateTimeField(db_index=True, null=True)),
                ('task_date', models.DateTimeField(db_index=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('sent_to', models.CharField(max_length=100, null=True)),
                ('sent_date', models.DateTimeField(db_index=True, null=True)),
                ('isActive', models.IntegerField(default=0)),
                ('attachement', models.TextField()),
                ('remarks', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product_sr_no', models.CharField(max_length=100, null=True)),
                ('tracking_id', models.CharField(max_length=500, null=True)),
                ('certificate_number', models.CharField(max_length=500, null=True)),
                ('last_meeting_date', models.DateTimeField(db_index=True, null=True)),
            ],
        ),
    ]
