# Generated by Django 3.2.1 on 2022-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrackinghistory',
            name='doc_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctrackinghistory',
            name='doc_type',
            field=models.CharField(max_length=500),
        ),
    ]
