# Generated by Django 3.2.1 on 2024-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=500)),
                ('certificate_serial_number', models.CharField(max_length=500, null=True)),
                ('certificate_issue_date', models.DateTimeField(db_index=True, null=True)),
                ('product_name', models.CharField(max_length=300, null=True)),
                ('identification_no', models.CharField(max_length=300, null=True)),
                ('qualification_date', models.DateTimeField(db_index=True, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('bhd_no', models.CharField(max_length=100)),
                ('certificate_number', models.CharField(max_length=500, null=True)),
                ('certificate_date', models.DateTimeField(db_index=True, null=True)),
                ('audit_report_date', models.DateTimeField(db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
