# Generated by Django 3.2.1 on 2024-06-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctracking', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='audit_report_no',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
