# Generated by Django 3.2.1 on 2024-06-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctracking', '0003_certification_audit_report_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='software_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='telemetry_modules',
            field=models.TextField(null=True),
        ),
    ]
