# Generated by Django 3.2.1 on 2024-06-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctracking', '0004_auto_20240619_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='id_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='quantity',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
