# Generated by Django 3.2.1 on 2024-01-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqa',
            old_name='bugs',
            new_name='bugs_observation',
        ),
        migrations.RenameField(
            model_name='sqa',
            old_name='DueDate',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='sqa',
            old_name='requestDate',
            new_name='request_date',
        ),
        migrations.RenameField(
            model_name='sqa',
            old_name='platform',
            new_name='static_analysis_report',
        ),
        migrations.RenameField(
            model_name='sqa',
            old_name='selected_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='sqa',
            old_name='standard_compliance',
            new_name='unit_test',
        ),
        migrations.RemoveField(
            model_name='sqa',
            name='static_testing',
        ),
        migrations.RemoveField(
            model_name='sqa',
            name='unit_testing',
        ),
        migrations.AddField(
            model_name='sqa',
            name='eng_change_proposal',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='rtm',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='sdd',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='srs',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='stp',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='urd',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
