# Generated by Django 3.2.1 on 2024-01-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0002_auto_20240106_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqa',
            old_name='urd',
            new_name='ubd',
        ),
    ]
