# Generated by Django 3.2.1 on 2024-01-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0003_rename_urd_sqa_ubd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqa',
            old_name='ubd',
            new_name='urd',
        ),
    ]
