# Generated by Django 3.2.1 on 2024-01-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0004_rename_ubd_sqa_urd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqa',
            name='organization',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
