# Generated by Django 3.2.1 on 2024-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0005_sqa_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqa',
            name='software_type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
