# Generated by Django 3.2.1 on 2024-03-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0006_sqa_software_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqaHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sys_type', models.CharField(max_length=300)),
                ('system_name', models.CharField(max_length=300)),
                ('module_name', models.CharField(max_length=300)),
                ('module_id', models.CharField(max_length=300)),
                ('software_version', models.CharField(max_length=300)),
                ('sqa_certificate_no', models.CharField(max_length=300)),
                ('request_date', models.DateTimeField()),
                ('urd', models.CharField(max_length=300, null=True)),
                ('srs', models.CharField(max_length=300, null=True)),
                ('sdd', models.CharField(max_length=300, null=True)),
                ('rtm', models.CharField(max_length=300, null=True)),
                ('stp', models.CharField(max_length=300, null=True)),
                ('unit_test', models.CharField(max_length=300)),
                ('static_analysis_report', models.CharField(max_length=300)),
                ('assertion_density', models.CharField(max_length=300)),
                ('eng_change_proposal', models.CharField(max_length=300, null=True)),
                ('bugs_observation', models.CharField(max_length=300)),
                ('cyclomatic_complexity', models.CharField(max_length=300)),
                ('code_coverage', models.CharField(max_length=300)),
                ('functional_testing', models.CharField(max_length=300)),
                ('formal_testing', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('due_date', models.DateTimeField()),
                ('audit_completion_date', models.DateTimeField()),
                ('organization', models.CharField(max_length=300, null=True)),
                ('software_type', models.CharField(max_length=300, null=True)),
                ('remarks', models.TextField()),
                ('sqa', models.IntegerField()),
            ],
        ),
    ]
