# Generated by Django 3.2.1 on 2024-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0007_sqahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqa',
            name='attachment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='installation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='purpose',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='received_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='revision_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='revision_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='set_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='software_size',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='svc_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqa',
            name='svc_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='attachment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='installation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='purpose',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='received_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='revision_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='revision_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='set_no',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='software_size',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='svc_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='svc_no',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
