# Generated by Django 3.2.1 on 2024-04-27 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0009_auto_20240309_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqa',
            name='design_coverage',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='design_coverage',
            field=models.TextField(null=True),
        ),
    ]
