# Generated by Django 3.2.1 on 2024-05-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0010_auto_20240427_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqa',
            name='optional_system_types',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='optional_system_types',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
