# Generated by Django 3.2.1 on 2024-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqa', '0011_auto_20240526_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqa',
            name='installation_date_obs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sqahistory',
            name='installation_date_obs',
            field=models.TextField(null=True),
        ),
    ]
