# Generated by Django 3.2.1 on 2022-09-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveMotors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('system', models.CharField(max_length=300)),
                ('motor_id', models.CharField(max_length=300)),
                ('qualification_insulation_lining_propellant_rm', models.CharField(max_length=300)),
                ('qualification_insulation_lining_propellant_rm_remarks', models.TextField()),
                ('acceptance_casting', models.CharField(max_length=300)),
                ('acceptance_casting_remarks', models.TextField()),
                ('sandblasting', models.CharField(max_length=300)),
                ('sandblasting_remarks', models.TextField()),
                ('insulation', models.CharField(max_length=300)),
                ('insulation_remarks', models.TextField()),
                ('ut_rt_insulated_case', models.CharField(max_length=300)),
                ('ut_rt_insulated_case_remarks', models.TextField()),
                ('acceptance_silver_material', models.CharField(max_length=300)),
                ('acceptance_silver_material_remarks', models.TextField()),
                ('silver_application', models.CharField(max_length=300)),
                ('silver_application_remarks', models.TextField()),
                ('formulation_tailoring_liner_propellant', models.CharField(max_length=300)),
                ('formulation_tailoring_liner_propellant_remarks', models.TextField()),
                ('conditioning_raw_materials', models.CharField(max_length=300)),
                ('conditioning_raw_materials_remarks', models.TextField()),
                ('lining', models.CharField(max_length=300)),
                ('lining_remarks', models.TextField()),
                ('casting', models.CharField(max_length=300)),
                ('casting_remarks', models.TextField()),
                ('curing', models.CharField(max_length=300)),
                ('curing_remarks', models.TextField()),
                ('liner_mechanical_properties', models.CharField(max_length=300)),
                ('liner_mechanical_properties_remarks', models.TextField()),
                ('propellant_mechanical_properties', models.CharField(max_length=300)),
                ('propellant_mechanical_properties_remarks', models.TextField()),
                ('interface_bond_strength', models.CharField(max_length=300)),
                ('interface_bond_strength_remarks', models.TextField()),
                ('propellant_burn_rate', models.CharField(max_length=300)),
                ('propellant_burn_rate_remarks', models.TextField()),
                ('trimming_Propellant_grain', models.CharField(max_length=300)),
                ('trimming_Propellant_grain_remarks', models.TextField()),
                ('mass_liner_insulation_propellant_srm', models.CharField(max_length=300)),
                ('mass_liner_insulation_propellant_srm_remarks', models.TextField()),
                ('ut_endoscopy_rt_grain', models.CharField(max_length=300)),
                ('ut_endoscopy_rt_grain_remarks', models.TextField()),
                ('ncr_status', models.CharField(max_length=300)),
                ('ncr_status_remarks', models.TextField()),
                ('overall_status', models.CharField(max_length=300)),
                ('overall_remarks', models.TextField()),
                ('attachments', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
