# Generated by Django 3.2.1 on 2023-09-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.CreateModel(
            name='AuditSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule', models.TextField()),
            ],
        ),
    ]
