# Generated by Django 3.2.1 on 2023-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300)),
                ('senior_directorate', models.CharField(max_length=500)),
                ('site', models.CharField(max_length=500)),
                ('test_report_no', models.CharField(max_length=100)),
                ('job_card_no', models.CharField(max_length=100)),
                ('test_report_date', models.DateField()),
                ('product_name', models.CharField(max_length=300)),
                ('id_no', models.CharField(max_length=100)),
                ('lot_no_lot_size', models.CharField(max_length=200)),
                ('test_name', models.CharField(max_length=300)),
                ('test_type', models.CharField(max_length=300)),
                ('qualification_standard', models.CharField(max_length=300)),
                ('test_specifications', models.CharField(max_length=300)),
                ('results', models.CharField(max_length=300)),
                ('remarks', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('assigned_by', models.CharField(max_length=100)),
                ('assigned_date', models.DateField()),
                ('assigned_to', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('status', models.CharField(max_length=355)),
                ('remarks', models.TextField()),
                ('task_date', models.DateField(null=True)),
                ('follow_up', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSummaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(null=True)),
                ('task_name', models.TextField()),
                ('assigned_by', models.CharField(max_length=100)),
                ('assigned_date', models.DateField()),
                ('assigned_to', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('status', models.CharField(max_length=355)),
                ('remarks', models.TextField()),
                ('task_date', models.DateField(null=True)),
                ('follow_up', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
