# Generated by Django 3.2.1 on 2022-08-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('assigned_by', models.CharField(max_length=100)),
                ('assigned_date', models.DateField()),
                ('assigned_to', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('status', models.CharField(max_length=355)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
