# Generated by Django 3.2.1 on 2022-09-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksummary',
            name='task_date',
            field=models.DateField(null=True),
        ),
    ]
