# Generated by Django 3.2.1 on 2022-09-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_tasksummary_task_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=300)),
                ('senior_directorate', models.CharField(max_length=500)),
                ('site', models.CharField(max_length=500)),
                ('test_report_no', models.CharField(max_length=100)),
                ('job_card_no', models.CharField(max_length=100)),
                ('test_report_date', models.DateField()),
                ('product_name', models.CharField(max_length=300)),
                ('id_no', models.CharField(max_length=100)),
                ('lot_no_lot_size', models.CharField(max_length=200)),
                ('test_name', models.CharField(max_length=300)),
                ('test_type', models.CharField(max_length=300)),
                ('qualification_standard', models.CharField(max_length=300)),
                ('test_specifications', models.CharField(max_length=300)),
                ('results', models.CharField(max_length=300)),
                ('remarks', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
