# Generated by Django 3.2.1 on 2022-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_ocrdatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksummary',
            name='follow_up',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
