# Generated by Django 3.2.1 on 2022-10-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0004_tasksummary_follow_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSummaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('assigned_by', models.CharField(max_length=100)),
                ('assigned_date', models.DateField()),
                ('assigned_to', models.CharField(max_length=255)),
                ('target_date', models.DateField()),
                ('status', models.CharField(max_length=355)),
                ('remarks', models.TextField()),
                ('task_date', models.DateField(null=True)),
                ('follow_up', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
