# Generated by Django 3.2.1 on 2022-10-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_tasksummaryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksummaryhistory',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
    ]
