# Generated by Django 3.2.1 on 2022-07-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_type', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100, null=True)),
                ('receive_date', models.DateTimeField(db_index=True, null=True)),
                ('marked_to', models.CharField(max_length=100, null=True)),
                ('marked_date', models.DateTimeField(db_index=True, null=True)),
                ('due_date', models.DateTimeField(db_index=True, null=True)),
                ('task_date', models.DateTimeField(db_index=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('sent_to', models.CharField(max_length=100, null=True)),
                ('sent_date', models.DateTimeField(db_index=True, null=True)),
                ('isActive', models.IntegerField(default=0)),
                ('attachement', models.TextField()),
                ('remarks', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
