# Generated by Django 3.2.1 on 2024-06-18 22:06

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import usermanagement.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=500)),
                ('doc_type', models.CharField(max_length=500)),
                ('sender', models.CharField(max_length=500, null=True)),
                ('receive_date', models.DateTimeField(db_index=True, null=True)),
                ('marked_to', models.CharField(max_length=500, null=True)),
                ('marked_date', models.DateTimeField(db_index=True, null=True)),
                ('due_date', models.DateTimeField(db_index=True, null=True)),
                ('task_date', models.DateTimeField(db_index=True, null=True)),
                ('status', models.CharField(max_length=500, null=True)),
                ('sent_to', models.CharField(max_length=500, null=True)),
                ('sent_date', models.DateTimeField(db_index=True, null=True)),
                ('isActive', models.IntegerField(default=0)),
                ('attachement', models.TextField()),
                ('remarks', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product_sr_no', models.CharField(max_length=500, null=True)),
                ('tracking_id', models.CharField(max_length=500, null=True)),
                ('certificate_number', models.CharField(max_length=500, null=True)),
                ('last_meeting_date', models.DateTimeField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_roles', models.CharField(max_length=555)),
                ('relif_roles', models.CharField(max_length=555)),
                ('flight_roles', models.CharField(max_length=555)),
                ('motor_roles', models.CharField(max_length=555)),
                ('battery_roles', models.CharField(max_length=555, null=True)),
                ('pyro_roles', models.CharField(max_length=555, null=True)),
                ('bhd_roles', models.CharField(max_length=555, null=True)),
                ('task_roles', models.CharField(max_length=555, null=True)),
                ('qms_roles', models.CharField(max_length=555, null=True)),
                ('cesp_roles', models.CharField(max_length=555, null=True)),
                ('sqa_roles', models.CharField(max_length=555, null=True)),
                ('emc_roles', models.CharField(max_length=555, null=True)),
                ('reliability_roles', models.CharField(max_length=555, null=True)),
                ('power_roles', models.CharField(max_length=555, null=True)),
                ('user_id', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(max_length=300)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', usermanagement.manager.UserManager()),
            ],
        ),
    ]
