# Generated by Django 3.2.1 on 2022-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctracking',
            name='product_sr_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
