# Generated by Django 3.2.1 on 2022-09-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_doctracking_product_sr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctracking',
            name='doc_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctracking',
            name='doc_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctracking',
            name='marked_to',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctracking',
            name='product_sr_no',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctracking',
            name='remarks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctracking',
            name='sender',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctracking',
            name='sent_to',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctracking',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
