from rest_framework.serializers import Serializer
from rest_framework.fields import CharField, IntegerField, DateTimeField



class ActiveMotorSerializer(Serializer):
    id = IntegerField()
    system = CharField()
    motor_id = CharField()
    qualification_insulation_lining_propellant_rm= CharField()
    qualification_insulation_lining_propellant_rm_remarks = CharField()
    acceptance_casting = CharField()
    acceptance_casting_remarks = CharField()
    sandblasting = CharField()
    sandblasting_remarks = CharField()
    insulation = CharField()
    insulation_remarks = CharField()
    ut_rt_insulated_case = CharField()
    ut_rt_insulated_case_remarks = CharField()
    acceptance_silver_material = CharField()
    acceptance_silver_material_remarks = CharField()
    silver_application = CharField()
    silver_application_remarks = CharField()
    formulation_tailoring_liner_propellant = CharField()
    formulation_tailoring_liner_propellant_remarks = CharField()
    conditioning_raw_materials = CharField()
    conditioning_raw_materials_remarks = CharField()
    lining = CharField()
    lining_remarks = CharField()
    casting =  CharField()
    casting_remarks = CharField()
    curing = CharField()
    curing_remarks = CharField()
    liner_mechanical_properties = CharField()
    liner_mechanical_properties_remarks = CharField()
    propellant_mechanical_properties = CharField()
    propellant_mechanical_properties_remarks = CharField()
    interface_bond_strength =  CharField()
    interface_bond_strength_remarks = CharField()
    propellant_burn_rate = CharField()
    propellant_burn_rate_remarks = CharField()
    trimming_Propellant_grain =  CharField()
    trimming_Propellant_grain_remarks = CharField()
    mass_liner_insulation_propellant_srm = CharField()
    mass_liner_insulation_propellant_srm_remarks = CharField()
    ut_endoscopy_rt_grain =  CharField()
    ut_endoscopy_rt_grain_remarks = CharField()
    ncr_status  = CharField()
    ncr_status_remarks = CharField()
    overall_status = CharField()
    overall_remarks = CharField()
    attachments =  CharField()
    Created_at = DateTimeField()



