from django.db import models

# Create your models here.
class Emc(models.Model):
    id = models.AutoField(primary_key=True)
    org_type = models.CharField(max_length=300)
    sys_type = models.CharField(max_length=300)
    sys_name = models.CharField(max_length=300)
    module_name = models.CharField(max_length=300,null=True)
    emi_emc_id = models.CharField(max_length=300, null=True)
    lot_no = models.CharField(max_length=300, null=True)
    design_version = models.CharField(max_length=300, null=True)
    test_requirements = models.CharField(max_length=300,null=True)
    test_conducted = models.CharField(max_length=300,null=True)
    test_compliance = models.CharField(max_length=300,null=True)
    compliance_status = models.CharField(max_length=300,null=True)
    report_status = models.CharField(max_length=300,null=True)
    compliance_date = models.DateTimeField(auto_now_add=False,null=True)
    remarks = models.TextField(null=True)
    ce_101 = models.CharField(max_length=300,null=True)
    ce_102 = models.CharField(max_length=300,null=True)
    ce_106 = models.CharField(max_length=300,null=True)
    re_101 = models.CharField(max_length=300,null=True)
    re_102 = models.CharField(max_length=300,null=True)
    re_103 = models.CharField(max_length=300,null=True)
    cs_101 = models.CharField(max_length=300,null=True)
    cs_103 = models.CharField(max_length=300,null=True)
    cs_104 = models.CharField(max_length=300,null=True)
    cs_105 = models.CharField(max_length=300,null=True)
    cs_109 = models.CharField(max_length=300,null=True)
    cs_114 = models.CharField(max_length=300,null=True)
    cs_115 = models.CharField(max_length=300,null=True)
    cs_116 = models.CharField(max_length=300,null=True)
    cs_117 = models.CharField(max_length=300,null=True)
    cs_118 = models.CharField(max_length=300,null=True)
    rs_101 = models.CharField(max_length=300,null=True)
    rs_103 = models.CharField(max_length=300,null=True)
    rs_105 = models.CharField(max_length=300,null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class EmcHistory(models.Model):
    id = models.AutoField(primary_key=True)
    emc_id = models.IntegerField(null=True)
    org_type = models.CharField(max_length=300)
    sys_type = models.CharField(max_length=300)
    sys_name = models.CharField(max_length=300)
    module_name = models.CharField(max_length=300,null=True)
    emi_emc_id = models.CharField(max_length=300, null=True)
    lot_no = models.CharField(max_length=300, null=True)
    design_version = models.CharField(max_length=300, null=True)
    test_requirements = models.CharField(max_length=300,null=True)
    test_conducted = models.CharField(max_length=300,null=True)
    test_compliance = models.CharField(max_length=300,null=True)
    compliance_status = models.CharField(max_length=300,null=True)
    report_status = models.CharField(max_length=300,null=True)
    compliance_date = models.DateTimeField(auto_now_add=False,null=True)
    remarks = models.TextField(null=True)
    ce_101 = models.CharField(max_length=300,null=True)
    ce_102 = models.CharField(max_length=300,null=True)
    ce_106 = models.CharField(max_length=300,null=True)
    re_101 = models.CharField(max_length=300,null=True)
    re_102 = models.CharField(max_length=300,null=True)
    re_103 = models.CharField(max_length=300,null=True)
    cs_101 = models.CharField(max_length=300,null=True)
    cs_103 = models.CharField(max_length=300,null=True)
    cs_104 = models.CharField(max_length=300,null=True)
    cs_105 = models.CharField(max_length=300,null=True)
    cs_109 = models.CharField(max_length=300,null=True)
    cs_114 = models.CharField(max_length=300,null=True)
    cs_115 = models.CharField(max_length=300,null=True)
    cs_116 = models.CharField(max_length=300,null=True)
    cs_117 = models.CharField(max_length=300,null=True)
    cs_118 = models.CharField(max_length=300,null=True)
    rs_101 = models.CharField(max_length=300,null=True)
    rs_103 = models.CharField(max_length=300,null=True)
    rs_105 = models.CharField(max_length=300,null=True)
    created_at = models.DateTimeField(auto_now_add=True)