from rest_framework.serializers import Serializer
from .models import *
from rest_framework.fields import CharField, IntegerField, DateTimeField


class EmcSerializer(Serializer):
    id = IntegerField()
    org_type = CharField()
    sys_type = CharField()
    sys_name = CharField()
    design_version = CharField()
    lot_no = CharField()
    module_name = CharField()
    emi_emc_id = CharField()
    test_requirements = CharField()
    test_conducted = CharField()
    test_compliance = CharField()
    compliance_status = CharField()
    report_status = CharField()
    compliance_date = CharField()
    remarks = CharField()
    ce_101 = CharField()
    ce_102 = CharField()
    ce_106 = CharField()
    re_101 = CharField()
    re_102 = CharField()
    re_103 = CharField()
    cs_101 = CharField()
    cs_103 = CharField()
    cs_104 = CharField()
    cs_105 = CharField()
    cs_109 = CharField()
    cs_114 = CharField()
    cs_115 = CharField()
    cs_116 = CharField()
    cs_117 = CharField()
    cs_118 = CharField()
    rs_101 = CharField()
    rs_103 = CharField()
    rs_105 = CharField()

class EmcHistorySerializer(Serializer):
    id = IntegerField()
    emc_id = IntegerField()
    org_type = CharField()
    sys_type = CharField()
    sys_name = CharField()
    design_version = CharField()
    lot_no = CharField()
    module_name = CharField()
    emi_emc_id = CharField()
    test_requirements = CharField()
    test_conducted = CharField()
    test_compliance = CharField()
    compliance_status = CharField()
    report_status = CharField()
    compliance_date = CharField()
    ce_101 = CharField()
    ce_102 = CharField()
    ce_106 = CharField()
    re_101 = CharField()
    re_102 = CharField()
    re_103 = CharField()
    cs_101 = CharField()
    cs_103 = CharField()
    cs_104 = CharField()
    cs_105 = CharField()
    cs_109 = CharField()
    cs_114 = CharField()
    cs_115 = CharField()
    cs_116 = CharField()
    cs_117 = CharField()
    cs_118 = CharField()
    rs_101 = CharField()
    rs_103 = CharField()
    rs_105 = CharField()